<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('productos', function (Blueprint $table) {
            $table->id();
            $table->foreignId('sector_id')->constrained('sectors')->restrictOnDelete();
            $table->string('codigo', 50);
            $table->string('nombre', 500);
            $table->boolean('activo')->default(true);
            $table->timestamps();

            $table->index(['sector_id', 'codigo']);
            $table->index('activo');
        });

        $productos = [
            ['sector_codigo' => '04', 'codigo' => '401103', 'nombre' => 'Documentos metodológicos'],
            ['sector_codigo' => '17', 'codigo' => '1702007', 'nombre' => 'Servicio de apoyo financiero para proyectos productivos'],
            ['sector_codigo' => '17', 'codigo' => '1702009', 'nombre' => 'Servicio de apoyo financiero para el acceso a activos productivos y de comercialización'],
            ['sector_codigo' => '17', 'codigo' => '1702035', 'nombre' => 'Servicio de educación informal en Buenas Prácticas Agrícolas y producción sostenible'],
            ['sector_codigo' => '17', 'codigo' => '1702037', 'nombre' => 'Servicio de fortalecimiento de capacidades locales'],
            ['sector_codigo' => '17', 'codigo' => '1702038', 'nombre' => 'Servicio de apoyo a la comercialización'],
            ['sector_codigo' => '17', 'codigo' => '1702040', 'nombre' => 'Servicio de fomento a la asociatividad'],
            ['sector_codigo' => '17', 'codigo' => '1703006', 'nombre' => 'Servicio de apoyo financiero para el acceso al crédito agropecuario y rural'],
            ['sector_codigo' => '17', 'codigo' => '1704003', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '17', 'codigo' => '1704017', 'nombre' => 'Servicio de apoyo para el fomento de la formalidad'],
            ['sector_codigo' => '17', 'codigo' => '1707069', 'nombre' => 'Servicio de divulgación y socialización'],
            ['sector_codigo' => '17', 'codigo' => '1708032', 'nombre' => 'Parcelas, módulos y unidades demostrativas adecuadas'],
            ['sector_codigo' => '17', 'codigo' => '1708051', 'nombre' => 'Servicio de información actualizado'],
            ['sector_codigo' => '17', 'codigo' => '1709034', 'nombre' => 'Infraestructura de pos cosecha adecuada'],
            ['sector_codigo' => '17', 'codigo' => '1709106', 'nombre' => 'Servicio de apoyo a la comercialización de las cadenas agrícolas, forestales, pecuarias, pesqueras y acuícolas'],
            ['sector_codigo' => '17', 'codigo' => '1709114', 'nombre' => 'Bancos de maquinaria y equipos para la producción agropecuaria dotado'],
            ['sector_codigo' => '17', 'codigo' => '1709072', 'nombre' => 'Plaza de Ferias adecuada'],
            ['sector_codigo' => '17', 'codigo' => '1709034', 'nombre' => 'Infraestructura de pos cosecha adecuada'],
            ['sector_codigo' => '17', 'codigo' => '1709055', 'nombre' => 'Infraestructura para el almacenamiento construida'],
            ['sector_codigo' => '17', 'codigo' => '1709075', 'nombre' => 'Plaza de Ferias construida'],
            ['sector_codigo' => '17', 'codigo' => '1709081', 'nombre' => 'Plaza de mercado construidas'],
            ['sector_codigo' => '19', 'codigo' => '1903003', 'nombre' => 'Servicio de apoyo financiero para dotar con bienes y Servicio de interés para la salud pública'],
            ['sector_codigo' => '19', 'codigo' => '1903011', 'nombre' => 'Servicio de inspección, vigilancia y control'],
            ['sector_codigo' => '19', 'codigo' => '1903023', 'nombre' => 'Servicio de asistencia técnica en inspección, vigilancia y control'],
            ['sector_codigo' => '19', 'codigo' => '1903034', 'nombre' => 'Servicio deasistencia técnica'],
            ['sector_codigo' => '19', 'codigo' => '1903035', 'nombre' => 'Servicio de inspección, vigilancia y control de los factores del riesgo del ambiente que afectan la salud humana'],
            ['sector_codigo' => '19', 'codigo' => '1903042', 'nombre' => 'Servicio de vigilancia y control sanitario de los factores de riesgo para la salud, en los establecimientos y espacios que pueden generar riesgos para la población.'],
            ['sector_codigo' => '19', 'codigo' => '1903057', 'nombre' => 'Servicio de promoción, prevención, vigilancia y control de vectores y zoonosis'],
            ['sector_codigo' => '19', 'codigo' => '1905012', 'nombre' => 'Cuartos fríos adecuados'],
            ['sector_codigo' => '19', 'codigo' => '1905015', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '19', 'codigo' => '1905024', 'nombre' => 'Servicio de gestión del riesgo para abordar situaciones de salud relacionadas con condiciones ambientales'],
            ['sector_codigo' => '19', 'codigo' => '1905037', 'nombre' => 'Documentos de investigación'],
            ['sector_codigo' => '19', 'codigo' => '1905040', 'nombre' => 'Servicio de certificación de discapacidad para las personas con discapacidad'],
            ['sector_codigo' => '19', 'codigo' => '1905041', 'nombre' => 'Servicio de atención psicosocial a víctimas del conflicto armado'],
            ['sector_codigo' => '19', 'codigo' => '1905050', 'nombre' => 'Servicio de asistencia técnica'],
            ['sector_codigo' => '19', 'codigo' => '1905053', 'nombre' => 'Documentos de evaluación'],
            ['sector_codigo' => '19', 'codigo' => '1905054', 'nombre' => 'Servicio de promoción de la salud'],
            ['sector_codigo' => '19', 'codigo' => '1906002', 'nombre' => 'Hospitales de primer nivel de atención ampliados'],
            ['sector_codigo' => '19', 'codigo' => '1906004', 'nombre' => 'Servicio de atención en salud a la población'],
            ['sector_codigo' => '19', 'codigo' => '1906009', 'nombre' => 'Hospitales de segundo nivel de atención ampliados'],
            ['sector_codigo' => '19', 'codigo' => '1906016', 'nombre' => 'Hospitales de tercer nivel de atención ampliados'],
            ['sector_codigo' => '19', 'codigo' => '1906022', 'nombre' => 'Servicio de apoyo a la prestación del servicio de transporte de pacientes'],
            ['sector_codigo' => '19', 'codigo' => '1906025', 'nombre' => 'Servicio de apoyo financiero para el fortalecimiento patrimonial de las empresas prestadoras de salud con participación financiera de las entidades territoriales'],
            ['sector_codigo' => '19', 'codigo' => '1906026', 'nombre' => 'Servicio de apoyo para la dotación hospitalaria'],
            ['sector_codigo' => '19', 'codigo' => '1906028', 'nombre' => 'Servicio para la habilitación y la rehabilitación funcional'],
            ['sector_codigo' => '19', 'codigo' => '1906034', 'nombre' => 'Estudios de preinversión'],
            ['sector_codigo' => '19', 'codigo' => '1906035', 'nombre' => 'Servicio de apoyo financiero para la atención en salud a la población'],
            ['sector_codigo' => '19', 'codigo' => '1906036', 'nombre' => 'Servicio de apoyo financiero para la reorganización de redes de prestación de servicios de salud'],
            ['sector_codigo' => '19', 'codigo' => '1906038', 'nombre' => 'Documentos metodológicos'],
            ['sector_codigo' => '19', 'codigo' => '1906044', 'nombre' => 'Servicio de afiliaciones al régimen subsidiado del Sistema General de Seguridad Social'],
            ['sector_codigo' => '21', 'codigo' => '2101002', 'nombre' => 'Estudios de pre inversión'],
            ['sector_codigo' => '21', 'codigo' => '2101006', 'nombre' => 'Gasoducto troncal mejorado'],
            ['sector_codigo' => '21', 'codigo' => '2101011', 'nombre' => 'Servicio de apoyo financiero para la financiación de proyectos de infraestructura para el servicio público de gas'],
            ['sector_codigo' => '21', 'codigo' => '2102008', 'nombre' => 'Documentos de lineamientos técnicos'],
            ['sector_codigo' => '21', 'codigo' => '2102010', 'nombre' => 'Redes de alumbrado público ampliadas'],
            ['sector_codigo' => '21', 'codigo' => '2102021', 'nombre' => 'Redes del sistema de transmisión regional construida'],
            ['sector_codigo' => '21', 'codigo' => '2102038', 'nombre' => 'Central de generación fotovoltaica construida'],
            ['sector_codigo' => '21', 'codigo' => '2102058', 'nombre' => 'Unidades de generación fotovoltaica de energía eléctrica instaladas'],
            ['sector_codigo' => '21', 'codigo' => '2102062', 'nombre' => 'Servicios de apoyo a la implementación de fuentes no convencionales de energía'],
            ['sector_codigo' => '21', 'codigo' => '2102063', 'nombre' => 'Servicios de apoyo a la implementacion de medidas de eficiencia energética'],
            ['sector_codigo' => '21', 'codigo' => '2103011', 'nombre' => 'Servicio de divulgación para la atención y disminución de la conflictividad del sector de hidrocarburos'],
            ['sector_codigo' => '21', 'codigo' => '2103024', 'nombre' => 'Servicio de educación informal en temas de hidrocarburos'],
            ['sector_codigo' => '21', 'codigo' => '2104009', 'nombre' => 'Servicio de divulgación del sector minero'],
            ['sector_codigo' => '22', 'codigo' => '2201006', 'nombre' => 'Servicio de asistencia técnica en educación inicial, preescolar, básica y media'],
            ['sector_codigo' => '22', 'codigo' => '2201017', 'nombre' => 'Servicio de fomento para el acceso a la educación inicial, preescolar, básica y media.'],
            ['sector_codigo' => '22', 'codigo' => '2201028', 'nombre' => 'Servicio de apoyo a la permanencia con alimentación escolar'],
            ['sector_codigo' => '22', 'codigo' => '2201029', 'nombre' => 'Servicio de apoyo a la permanencia con transporte escolar'],
            ['sector_codigo' => '22', 'codigo' => '2201034', 'nombre' => 'Servicio educativos de promoción del bilingüismo'],
            ['sector_codigo' => '22', 'codigo' => '2201035', 'nombre' => 'Servicio de articulación entre la educación media y el sector productivo.'],
            ['sector_codigo' => '22', 'codigo' => '2201037', 'nombre' => 'Servicio de atención integral para la primera infancia'],
            ['sector_codigo' => '22', 'codigo' => '2201038', 'nombre' => 'Servicio de docencia escolar'],
            ['sector_codigo' => '22', 'codigo' => '2201044', 'nombre' => 'Servicios conexos a la prestación del servicio educativo oficial'],
            ['sector_codigo' => '22', 'codigo' => '2201048', 'nombre' => 'Servicios de información en materia educativa'],
            ['sector_codigo' => '22', 'codigo' => '2201049', 'nombre' => 'Servicio de educación informal'],
            ['sector_codigo' => '22', 'codigo' => '2201050', 'nombre' => 'Servicio de accesibilidad a contenidos web para fines pedagógicos'],
            ['sector_codigo' => '22', 'codigo' => '2201051', 'nombre' => 'Infraestructura educativa construida'],
            ['sector_codigo' => '22', 'codigo' => '2201052', 'nombre' => 'Infraestructura educativa mejorada'],
            ['sector_codigo' => '22', 'codigo' => '2201067', 'nombre' => 'Servicio de apoyo para el fortalecimiento de escuelas de padres'],
            ['sector_codigo' => '22', 'codigo' => '2201069', 'nombre' => 'Infraestructura educativa dotada'],
            ['sector_codigo' => '22', 'codigo' => '2201076', 'nombre' => 'Servicio de asistencia técnica a comunidades en fortalecimiento del tejido social y construcción de escenarios comunitarios protectores de derechos'],
            ['sector_codigo' => '22', 'codigo' => '2201081', 'nombre' => 'Servicio de apoyo a la atención integral para la convivencia escolar'],
            ['sector_codigo' => '22', 'codigo' => '2201084', 'nombre' => 'Servicio de apoyo pedagógico para  la oferta de educación inclusiva para preescolar, básica y media'],
            ['sector_codigo' => '22', 'codigo' => '2202049', 'nombre' => 'Estudios de preinversión'],
            ['sector_codigo' => '22', 'codigo' => '2202050', 'nombre' => 'Ambientes de aprendizaje dotados'],
            ['sector_codigo' => '22', 'codigo' => '2202065', 'nombre' => 'Servicio de apoyo financiero para el acceso y permanencia a la educación superior'],
            ['sector_codigo' => '22', 'codigo' => '2202071', 'nombre' => 'Sedes de instituciones de educación superior  construidas'],
            ['sector_codigo' => '22', 'codigo' => '2202079', 'nombre' => 'Servicio de apoyo para la permanencia a la educación superior'],
            ['sector_codigo' => '22', 'codigo' => '4599008', 'nombre' => 'Sede construida y dotada'],
            ['sector_codigo' => '23', 'codigo' => '2301024', 'nombre' => 'Servicio de acceso y uso de Tecnologías de la Información y las Comunicaciones'],
            ['sector_codigo' => '23', 'codigo' => '2301028', 'nombre' => 'Servicio de conexiones a redes de servicio portador'],
            ['sector_codigo' => '23', 'codigo' => '2301030', 'nombre' => 'Servicio de educación informal en tecnologías de la información y las comunicaciones.'],
            ['sector_codigo' => '23', 'codigo' => '2301047', 'nombre' => 'Servicio de difusión para promover el uso de internet'],
            ['sector_codigo' => '23', 'codigo' => '2301062', 'nombre' => 'Servicio de apoyo en tecnologías de la información y las comunicaciones para la educación básica, primaria y secundaria'],
            ['sector_codigo' => '23', 'codigo' => '2301075', 'nombre' => 'Servicio de Información implementado'],
            ['sector_codigo' => '23', 'codigo' => '2301079', 'nombre' => 'Servicio de acceso zonas digitales'],
            ['sector_codigo' => '23', 'codigo' => '2302002', 'nombre' => 'Contenidos digitales'],
            ['sector_codigo' => '23', 'codigo' => '2302007', 'nombre' => 'Documentos metodológicos'],
            ['sector_codigo' => '23', 'codigo' => '2302021', 'nombre' => 'Servicio de asistencia técnica a emprendedores y empresas'],
            ['sector_codigo' => '23', 'codigo' => '2302024', 'nombre' => 'Servicio de asistencia técnica para la implementación de la Estrategia de Gobierno digital'],
            ['sector_codigo' => '23', 'codigo' => '2302041', 'nombre' => 'Servicio de promoción de la participación ciudadana para el fomento del diálogo con el Estado'],
            ['sector_codigo' => '23', 'codigo' => '2302065', 'nombre' => 'Servicio de Educación informal sobre las Tecnologías de la Información y las Comunicaciones con enfoque diferencial'],
            ['sector_codigo' => '23', 'codigo' => '2302068', 'nombre' => 'Servicio de educación informal para aumentar la calidad y cantidad de talento humano para la industria TI'],
            ['sector_codigo' => '23', 'codigo' => '2302074', 'nombre' => 'Servicio de producción y/o coproducción de contenidos convergentes'],
            ['sector_codigo' => '23', 'codigo' => '2302081', 'nombre' => 'Servicio de asistencia técnica para el fomento de contenidos'],
            ['sector_codigo' => '23', 'codigo' => '2302089', 'nombre' => 'Servicio de contenidos audiovisuales'],
            ['sector_codigo' => '23', 'codigo' => '2302094', 'nombre' => 'Servicio de circulación de contenidos convergentes'],
            ['sector_codigo' => '23', 'codigo' => '2302101', 'nombre' => '#N/A'],
            ['sector_codigo' => '24', 'codigo' => '2402006', 'nombre' => 'Vía secundaria mejorada'],
            ['sector_codigo' => '24', 'codigo' => '2402015', 'nombre' => 'Puente construido en vía secundaria'],
            ['sector_codigo' => '24', 'codigo' => '2402041', 'nombre' => 'Vía terciaria mejorada'],
            ['sector_codigo' => '24', 'codigo' => '2402044', 'nombre' => 'Puente construido en vía terciaria'],
            ['sector_codigo' => '24', 'codigo' => '2402104', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '24', 'codigo' => '2402114', 'nombre' => 'Vía urbana mejorada'],
            ['sector_codigo' => '24', 'codigo' => '2402118', 'nombre' => 'Estudios de preinversión para la red vial regional'],
            ['sector_codigo' => '24', 'codigo' => '2402119', 'nombre' => 'Puente construido en vía urbana existente'],
            ['sector_codigo' => '24', 'codigo' => '2403084', 'nombre' => 'Estudios de preinversión'],
            ['sector_codigo' => '24', 'codigo' => '2409002', 'nombre' => 'Servicio de sensibilización a usuarios de los sistemas de transporte, en relación con la seguridad al desplazarse'],
            ['sector_codigo' => '24', 'codigo' => '2409007', 'nombre' => 'Servicio de asistencia técnica en temas de seguridad de transporte'],
            ['sector_codigo' => '24', 'codigo' => '2409023', 'nombre' => 'Servicio de sensibilización a los actores viales'],
            ['sector_codigo' => '24', 'codigo' => '2409039', 'nombre' => 'Vías con dispositivos de control y señalización'],
            ['sector_codigo' => '24', 'codigo' => '2409059', 'nombre' => 'Servicio de información implementado'],
            ['sector_codigo' => '32', 'codigo' => '3201003', 'nombre' => 'Servicio de asistencia técnica para la consolidación de negocios verdes'],
            ['sector_codigo' => '32', 'codigo' => '3201009', 'nombre' => 'Servicio de seguimiento y evaluación de los programas de recolección de residuos pos consumo'],
            ['sector_codigo' => '32', 'codigo' => '3202001', 'nombre' => 'Documentos de lineamientos técnicos para la conservación de la biodiversidad y sus servicios eco sistémicos'],
            ['sector_codigo' => '32', 'codigo' => '3202002', 'nombre' => 'Documentos de planeación para la conservación de la biodiversidad y sus servicios eco sistémicos'],
            ['sector_codigo' => '32', 'codigo' => '3202003', 'nombre' => 'Documentos de política para la conservación de la biodiversidad y sus servicio eco sistémicos'],
            ['sector_codigo' => '32', 'codigo' => '3202012', 'nombre' => 'Servicio de protección de ecosistemas'],
            ['sector_codigo' => '32', 'codigo' => '3202014', 'nombre' => 'Servicio de educación informal en el marco de la conservación de la biodiversidad y los Servicio ecostémicos'],
            ['sector_codigo' => '32', 'codigo' => '3202038', 'nombre' => 'Servicio de producción de plántulas en viveros'],
            ['sector_codigo' => '32', 'codigo' => '3202043', 'nombre' => 'Servicio apoyo financiero para la implementación de esquemas de pago por Servicio ambientales'],
            ['sector_codigo' => '32', 'codigo' => '3204019', 'nombre' => 'Servicio de información en biodiversidad'],
            ['sector_codigo' => '32', 'codigo' => '3206002', 'nombre' => 'Documentos de lineamientos técnicos para la gestión del cambio climático y un desarrollo bajo en carbono y resiliente al clima'],
            ['sector_codigo' => '32', 'codigo' => '4501061', 'nombre' => 'Servicio de atención integral a la fauna'],
            ['sector_codigo' => '33', 'codigo' => '3301018', 'nombre' => 'Casas de la cultura adecuadas'],
            ['sector_codigo' => '33', 'codigo' => '3301038', 'nombre' => 'Teatros adecuados'],
            ['sector_codigo' => '33', 'codigo' => '3301051', 'nombre' => 'Servicio de educación informal al sector artístico y cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301052', 'nombre' => 'Servicio de educación formal al sector artístico y cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301053', 'nombre' => 'Servicio de promoción de actividades culturales'],
            ['sector_codigo' => '33', 'codigo' => '3301054', 'nombre' => 'Servicio de apoyo financiero al sector artístico y cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301055', 'nombre' => 'Servicio de apoyo financiero para el desarrollo de prácticas artísticas y culturales'],
            ['sector_codigo' => '33', 'codigo' => '3301068', 'nombre' => 'Servicio de mantenimiento de infraestructura cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301070', 'nombre' => 'Documentos de lineamientos técnicos'],
            ['sector_codigo' => '33', 'codigo' => '3301073', 'nombre' => 'Servicio de circulación artística y cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301074', 'nombre' => 'Servicio de apoyo para la organización y la participación del sector artístico, cultural y la ciudadanía'],
            ['sector_codigo' => '33', 'codigo' => '3301075', 'nombre' => 'Bibliotecas construidas y dotadas'],
            ['sector_codigo' => '33', 'codigo' => '3301085', 'nombre' => 'Servicios bibliotecarios'],
            ['sector_codigo' => '33', 'codigo' => '3301093', 'nombre' => 'Centros culturales construidos y dotados'],
            ['sector_codigo' => '33', 'codigo' => '3301094', 'nombre' => 'Estudios y diseños de infraestructura cultural'],
            ['sector_codigo' => '33', 'codigo' => '3301098', 'nombre' => 'Servicio de acceso a materiales de lectura'],
            ['sector_codigo' => '33', 'codigo' => '3301100', 'nombre' => 'Servicio de divulgación y publicaciones'],
            ['sector_codigo' => '33', 'codigo' => '3301127', 'nombre' => 'Infraestructuras culturales dotadas'],
            ['sector_codigo' => '33', 'codigo' => '3301128', 'nombre' => 'Servicio de apoyo financiero para creadores y gestores culturales'],
            ['sector_codigo' => '33', 'codigo' => '3302018', 'nombre' => 'Servicio de educación para el trabajo en Escuelas Taller'],
            ['sector_codigo' => '33', 'codigo' => '3302019', 'nombre' => 'Servicio de educación informal a Vigías del Patrimonio'],
            ['sector_codigo' => '33', 'codigo' => '3302049', 'nombre' => 'Servicio de salvaguardia al patrimonio inmaterial'],
            ['sector_codigo' => '33', 'codigo' => '3302070', 'nombre' => 'Serviciode divulgación y publicación del Patrimonio cultural'],
            ['sector_codigo' => '33', 'codigo' => '3302076', 'nombre' => 'Servicio de desarrollo tecnológico e innovación de archivos electrónicos'],
            ['sector_codigo' => '35', 'codigo' => '3502002', 'nombre' => 'Documentos de lineamientos técnicos'],
            ['sector_codigo' => '35', 'codigo' => '3502003', 'nombre' => 'Servicio de asistencia técnica para el fortalecimiento de capacidades gerenciales'],
            ['sector_codigo' => '35', 'codigo' => '3502004', 'nombre' => 'Servicio de apoyo financiero para el mejoramiento de productos o procesos'],
            ['sector_codigo' => '35', 'codigo' => '3502012', 'nombre' => 'Servicio de apoyo para la modernización y fomento de la innovación empresarial'],
            ['sector_codigo' => '35', 'codigo' => '3502015', 'nombre' => 'Servicio para la formalización empresarial y de productos y/o Servicio'],
            ['sector_codigo' => '35', 'codigo' => '3502019', 'nombre' => 'Servicio de asistencia técnica y acompañamiento productivo y empresarial'],
            ['sector_codigo' => '35', 'codigo' => '3502038', 'nombre' => 'Servicio de apoyo financiero para la construcción de infraestructura turística'],
            ['sector_codigo' => '35', 'codigo' => '3502039', 'nombre' => 'Servicio de asistencia técnica a los entes territoriales para el desarrollo turístico'],
            ['sector_codigo' => '35', 'codigo' => '3502045', 'nombre' => 'Servicio de educación informal en asuntos turísticos'],
            ['sector_codigo' => '35', 'codigo' => '3502046', 'nombre' => 'Servicio de promoción turística'],
            ['sector_codigo' => '35', 'codigo' => '3502047', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '35', 'codigo' => '3502048', 'nombre' => 'Documentos normativos'],
            ['sector_codigo' => '35', 'codigo' => '3502053', 'nombre' => 'Centro turístico construido'],
            ['sector_codigo' => '35', 'codigo' => '3502055', 'nombre' => 'Centro turístico mantenido'],
            ['sector_codigo' => '35', 'codigo' => '3502078', 'nombre' => 'Malecón construido'],
            ['sector_codigo' => '35', 'codigo' => '3502093', 'nombre' => 'Servicios de información turística a nivel nacional'],
            ['sector_codigo' => '35', 'codigo' => '3502094', 'nombre' => 'Documentos de investigación sobre turismo'],
            ['sector_codigo' => '35', 'codigo' => '3502098', 'nombre' => 'Sendero turístico mejorado'],
            ['sector_codigo' => '35', 'codigo' => '3502116', 'nombre' => 'Servicio de asistencia técnica'],
            ['sector_codigo' => '36', 'codigo' => '3602032', 'nombre' => 'Servicio de asesoría técnica para el emprendimiento'],
            ['sector_codigo' => '39', 'codigo' => '3906011', 'nombre' => 'Servicio de apropiación social del conocimiento'],
            ['sector_codigo' => '40', 'codigo' => '4001002', 'nombre' => 'Servicio de asistencia técnica en proyectos de Vivienda'],
            ['sector_codigo' => '40', 'codigo' => '4001007', 'nombre' => 'Servicio de saneamiento y titulación de bienes fiscales'],
            ['sector_codigo' => '40', 'codigo' => '4001030', 'nombre' => 'Estudios de pre inversión e inversión'],
            ['sector_codigo' => '40', 'codigo' => '4001031', 'nombre' => 'Servicio de apoyo financiero para adquisición de vivienda'],
            ['sector_codigo' => '40', 'codigo' => '4001032', 'nombre' => 'Servicio de apoyo financiero para mejoramiento de vivienda'],
            ['sector_codigo' => '40', 'codigo' => '4001034', 'nombre' => 'Servicio de apoyo financiero para construcción de vivienda en sitio propio'],
            ['sector_codigo' => '40', 'codigo' => '4002016', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '40', 'codigo' => '4002019', 'nombre' => 'Espacio publico construido'],
            ['sector_codigo' => '40', 'codigo' => '4002020', 'nombre' => 'Espacio publico adecuado'],
            ['sector_codigo' => '40', 'codigo' => '4003006', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '40', 'codigo' => '4003009', 'nombre' => 'Servicio de Acueducto'],
            ['sector_codigo' => '40', 'codigo' => '4003010', 'nombre' => 'Servicio de Aseo'],
            ['sector_codigo' => '40', 'codigo' => '4003014', 'nombre' => 'Servicio de Alcantarillado'],
            ['sector_codigo' => '40', 'codigo' => '4003015', 'nombre' => 'Acueductos construidos'],
            ['sector_codigo' => '40', 'codigo' => '4003016', 'nombre' => 'Acueductos ampliados'],
            ['sector_codigo' => '40', 'codigo' => '4003017', 'nombre' => 'Acueductos optimizados'],
            ['sector_codigo' => '40', 'codigo' => '4003018', 'nombre' => 'Alcantarillados construidos'],
            ['sector_codigo' => '40', 'codigo' => '4003019', 'nombre' => 'Alcantarillados ampliados'],
            ['sector_codigo' => '40', 'codigo' => '4003042', 'nombre' => 'Estudios de pre inversión e inversión'],
            ['sector_codigo' => '40', 'codigo' => '4003046', 'nombre' => 'Servicio de apoyo financiero para capitalización de empresas'],
            ['sector_codigo' => '41', 'codigo' => '4101023', 'nombre' => 'Servicio de orientación y comunicación a las víctimas'],
            ['sector_codigo' => '41', 'codigo' => '4101025', 'nombre' => 'Servicio de ayuda y atención humanitaria'],
            ['sector_codigo' => '41', 'codigo' => '4101027', 'nombre' => 'Servicio de asistencia funeraria'],
            ['sector_codigo' => '41', 'codigo' => '4101031', 'nombre' => 'Servicios de implementaciónde medidas de satisfacción y acompañamiento a las víctimas del conflicto armado'],
            ['sector_codigo' => '41', 'codigo' => '4101038', 'nombre' => 'Servicio de asistencia técnica para la participación de las víctimas'],
            ['sector_codigo' => '41', 'codigo' => '4101042', 'nombre' => 'Servicio de apoyo para la seguridad alimentaria'],
            ['sector_codigo' => '41', 'codigo' => '4101063', 'nombre' => 'Servicios de asistencia técnica para la articulación interinstitucional en la implementación de la polìtica pública para las víctimas'],
            ['sector_codigo' => '41', 'codigo' => '4101068', 'nombre' => 'Servicios de divulgación de tematicas de memoria histórica'],
            ['sector_codigo' => '41', 'codigo' => '4101073', 'nombre' => 'Servicio de apoyo para la generación de ingresos'],
            ['sector_codigo' => '41', 'codigo' => '4101076', 'nombre' => 'Servicio de apoyo para el mejoramiento de condiciones de habitabilidad para población víctima de desplazamiento forzado'],
            ['sector_codigo' => '41', 'codigo' => '4101092', 'nombre' => 'Servicios de satisfacción y garantías de no repetición a víctimas del conflicto armado'],
            ['sector_codigo' => '41', 'codigo' => '4101103', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '41', 'codigo' => '4102041', 'nombre' => 'Servicio de asistencia técnica en el ciclo de políticas públicas de familia y otras relacionadas'],
            ['sector_codigo' => '41', 'codigo' => '4102042', 'nombre' => 'Servicio de asistencia técnica a comunidades en temas de fortalecimiento del tejido social y construcción de escenarios comunitarios protectores de derechos'],
            ['sector_codigo' => '41', 'codigo' => '4102045', 'nombre' => 'Servicios de educación informal a niños, niñas, adolescentes  y jóvenes para el reconocimiento de sus derechos'],
            ['sector_codigo' => '41', 'codigo' => '4102052', 'nombre' => 'Servicio de protección integral a niños, niñas, adolescentes y jóvenes'],
            ['sector_codigo' => '41', 'codigo' => '4103004', 'nombre' => 'Servicio de educación para el trabajo a la población vulnerable'],
            ['sector_codigo' => '41', 'codigo' => '4103005', 'nombre' => 'Servicio de asistencia técnica para el emprendimiento'],
            ['sector_codigo' => '41', 'codigo' => '4103010', 'nombre' => 'Servicio de gestión para la colocación de empleo'],
            ['sector_codigo' => '41', 'codigo' => '4103017', 'nombre' => 'Servicio de entrega de raciones de alimentos'],
            ['sector_codigo' => '41', 'codigo' => '4103025', 'nombre' => 'Centros comunitarios construidos'],
            ['sector_codigo' => '41', 'codigo' => '4103031', 'nombre' => 'Centros comunitarios dotados'],
            ['sector_codigo' => '41', 'codigo' => '4103052', 'nombre' => 'Servicio de gestión de oferta social para la población vulnerable'],
            ['sector_codigo' => '41', 'codigo' => '4103057', 'nombre' => 'Servicio de apoyo a unidades productivas individuales para la generación de ingresos'],
            ['sector_codigo' => '41', 'codigo' => '4103067', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '41', 'codigo' => '4104002', 'nombre' => 'Centros de protección social para el adulto mayor adecuados'],
            ['sector_codigo' => '41', 'codigo' => '4104006', 'nombre' => 'Centros de protección social para el adulto mayor construidos'],
            ['sector_codigo' => '41', 'codigo' => '4104007', 'nombre' => 'Centros de protección social para el adulto mayor dotados'],
            ['sector_codigo' => '41', 'codigo' => '4104008', 'nombre' => 'Servicio de atención y protección integral al adulto mayor'],
            ['sector_codigo' => '41', 'codigo' => '4104020', 'nombre' => 'Servicio de atención integral a población en condición de discapacidad'],
            ['sector_codigo' => '41', 'codigo' => '4104027', 'nombre' => 'Servicio de atención integral al habitante de la calle'],
            ['sector_codigo' => '41', 'codigo' => '4502001', 'nombre' => 'Servicio de promoción a la participación ciudadana'],
            ['sector_codigo' => '41', 'codigo' => '4599029', 'nombre' => 'Servicio de integración de la oferta pública'],
            ['sector_codigo' => '43', 'codigo' => '4301007', 'nombre' => 'Servicio de Escuelas Deportivas'],
            ['sector_codigo' => '43', 'codigo' => '4301011', 'nombre' => 'Parques recreativos adecuados'],
            ['sector_codigo' => '43', 'codigo' => '4301030', 'nombre' => 'Parque recreo-deportivo construido y dotado'],
            ['sector_codigo' => '43', 'codigo' => '4301037', 'nombre' => 'Servicio de promoción de la actividad física, la recreación y el deporte'],
            ['sector_codigo' => '43', 'codigo' => '4301038', 'nombre' => 'Servicio de organización de eventos recreativos comunitarios'],
            ['sector_codigo' => '43', 'codigo' => '4302001', 'nombre' => 'Servicio de preparación deportiva'],
            ['sector_codigo' => '43', 'codigo' => '4302002', 'nombre' => 'Servicio de apoyo financiero a atletas'],
            ['sector_codigo' => '43', 'codigo' => '4302004', 'nombre' => 'Servicio de organización de eventos deportivos de alto rendimiento'],
            ['sector_codigo' => '43', 'codigo' => '4302083', 'nombre' => 'Complejo deportivo de alto rendimiento construido y dotado'],
            ['sector_codigo' => '43', 'codigo' => '4302086', 'nombre' => 'Complejo deportivo de alto rendimiento adecuado'],
            ['sector_codigo' => '45', 'codigo' => '401104', 'nombre' => 'Documentos de estudios técnicos'],
            ['sector_codigo' => '45', 'codigo' => '4002016', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '45', 'codigo' => '4501001', 'nombre' => 'Servicio de asistencia técnica'],
            ['sector_codigo' => '45', 'codigo' => '4501004', 'nombre' => 'Servicio de promoción de convivencia y no repetición'],
            ['sector_codigo' => '45', 'codigo' => '4501026', 'nombre' => 'Documentos Planeacion'],
            ['sector_codigo' => '45', 'codigo' => '4501028', 'nombre' => 'Servicio de vigilancia a través de cámaras de seguridad'],
            ['sector_codigo' => '45', 'codigo' => '4501029', 'nombre' => 'Servicio de apoyo financiero para proyectos de convivencia y seguridad ciudadana'],
            ['sector_codigo' => '45', 'codigo' => '4501050', 'nombre' => 'Servicio de orientación a casos de violencia de género'],
            ['sector_codigo' => '45', 'codigo' => '4501053', 'nombre' => 'Servicio de apoyo financiero para la formación en carreras militares y policiales'],
            ['sector_codigo' => '45', 'codigo' => '4501069', 'nombre' => 'Infraestructura de soporte construida'],
            ['sector_codigo' => '45', 'codigo' => '4502001', 'nombre' => 'Servicio de promoción a la participación ciudadana'],
            ['sector_codigo' => '45', 'codigo' => '4502015', 'nombre' => 'Oficina para la atención y orientación ciudadana dotada'],
            ['sector_codigo' => '45', 'codigo' => '4502016', 'nombre' => 'Servicio de información implementado'],
            ['sector_codigo' => '45', 'codigo' => '4502017', 'nombre' => 'Servicio de información actualizado'],
            ['sector_codigo' => '45', 'codigo' => '4502022', 'nombre' => 'Servicio de asistencia técnica'],
            ['sector_codigo' => '45', 'codigo' => '4502030', 'nombre' => 'Documentos de investigación'],
            ['sector_codigo' => '45', 'codigo' => '4502032', 'nombre' => 'Documentos de lineamientos técnicos'],
            ['sector_codigo' => '45', 'codigo' => '4502033', 'nombre' => 'Servicio de integración de la oferta pública'],
            ['sector_codigo' => '45', 'codigo' => '4502034', 'nombre' => 'Servicio de educación informal'],
            ['sector_codigo' => '45', 'codigo' => '4502035', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '45', 'codigo' => '4502037', 'nombre' => 'Servicio de apoyo para el acceso a programas de educación para el trabajo y el desarrollo humano'],
            ['sector_codigo' => '45', 'codigo' => '4502038', 'nombre' => 'Servicio de promoción de la garantía de derechos'],
            ['sector_codigo' => '45', 'codigo' => '4599001', 'nombre' => 'Documentos de evaluación'],
            ['sector_codigo' => '45', 'codigo' => '4599002', 'nombre' => 'Servicio de saneamiento fiscal y financiero'],
            ['sector_codigo' => '45', 'codigo' => '4599006', 'nombre' => 'Estudios de preinversión'],
            ['sector_codigo' => '45', 'codigo' => '4599007', 'nombre' => 'Servicios tecnológicos'],
            ['sector_codigo' => '45', 'codigo' => '4599009', 'nombre' => 'Sedes construidas'],
            ['sector_codigo' => '45', 'codigo' => '4599011', 'nombre' => 'Sedes adecuadas'],
            ['sector_codigo' => '45', 'codigo' => '4599015', 'nombre' => 'Sedes adquiridas'],
            ['sector_codigo' => '45', 'codigo' => '4599016', 'nombre' => 'Sedes mantenidas'],
            ['sector_codigo' => '45', 'codigo' => '4599017', 'nombre' => 'Servicio de gestión documental'],
            ['sector_codigo' => '45', 'codigo' => '4599018', 'nombre' => 'Documentos de lineamientos técnicos'],
            ['sector_codigo' => '45', 'codigo' => '4599019', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '45', 'codigo' => '4599023', 'nombre' => 'Servicio de Implementación Sistemas de Gestión'],
            ['sector_codigo' => '45', 'codigo' => '4599025', 'nombre' => 'Servicios de información implementados'],
            ['sector_codigo' => '45', 'codigo' => '4599028', 'nombre' => 'Servicio de información actualizado'],
            ['sector_codigo' => '45', 'codigo' => '4599029', 'nombre' => 'Servicio de integración de la oferta pública'],
            ['sector_codigo' => '45', 'codigo' => '4599030', 'nombre' => 'Servicio de educación informal'],
            ['sector_codigo' => '45', 'codigo' => '4599031', 'nombre' => 'Servicio de asistencia técnica'],
            ['sector_codigo' => '45', 'codigo' => '4599032', 'nombre' => 'Documentos de política'],
            ['sector_codigo' => '45', 'codigo' => '4599034', 'nombre' => 'Sedes dotadas'],
            ['sector_codigo' => '45', 'codigo' => '4599037', 'nombre' => 'Servicio de actualización del Sistema de Gestión'],
            ['sector_codigo' => '45', 'codigo' => '4503002', 'nombre' => 'Servicio de educación informal'],
            ['sector_codigo' => '45', 'codigo' => '4503004', 'nombre' => 'Servicio de atención a emergencias y desastres'],
            ['sector_codigo' => '45', 'codigo' => '4503017', 'nombre' => 'Estudios de riesgo de desastres'],
            ['sector_codigo' => '45', 'codigo' => '4503018', 'nombre' => '"Servicio de monitoreo y seguimiento para la gestión del riesgo"'],
            ['sector_codigo' => '45', 'codigo' => '4503022', 'nombre' => 'Obras de infraestructura para la reducción del riesgo de desastres'],
            ['sector_codigo' => '45', 'codigo' => '4503023', 'nombre' => 'Documentos de planeación'],
            ['sector_codigo' => '45', 'codigo' => '4503028', 'nombre' => 'Servicios de apoyo para atención de  población afectada por situaciones de emergencia, desastre o declaratorias de calamidad pública'],
            ['sector_codigo' => '45', 'codigo' => '4503031', 'nombre' => 'Documentos de lineamientos técnicos'],
        ];

        $sectorIdsByCode = DB::table('sectors')->pluck('id', 'codigo');
        $now = now();

        foreach ($productos as $producto) {
            $sectorId = $sectorIdsByCode[$producto['sector_codigo']] ?? null;
            if (! $sectorId) {
                continue;
            }

            DB::table('productos')->insert([
                'sector_id' => $sectorId,
                'codigo' => $producto['codigo'],
                'nombre' => $producto['nombre'],
                'activo' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('productos');
    }
};
