<?php

return [
    'template_paths' => [
        'bank_plan_inversion' => env('BANK_TEMPLATE_FPE23', '/Users/jonathanjimenez/Library/CloudStorage/GoogleDrive-jonathan.c.jimenez@gmail.com/.shortcut-targets-by-id/1ftdkQPOwmPw0wysIQSHnbfiGKVzi279m/1737701 Parque Villa Margarita/01 Estructuracion/01 Formulacion/1.05 Banco de Proyectos/04 Plan de Inversion.xlsx'),
        'bank_plan_desarrollo' => env('BANK_TEMPLATE_FPE24', '/Users/jonathanjimenez/Library/CloudStorage/GoogleDrive-jonathan.c.jimenez@gmail.com/.shortcut-targets-by-id/1ftdkQPOwmPw0wysIQSHnbfiGKVzi279m/1737701 Parque Villa Margarita/01 Estructuracion/01 Formulacion/1.05 Banco de Proyectos/05 Plan de Desarrollo.xlsx'),
        'bank_cronograma' => env('BANK_TEMPLATE_FPE25', '/Users/jonathanjimenez/Library/CloudStorage/GoogleDrive-jonathan.c.jimenez@gmail.com/.shortcut-targets-by-id/1ftdkQPOwmPw0wysIQSHnbfiGKVzi279m/1737701 Parque Villa Margarita/01 Estructuracion/01 Formulacion/1.05 Banco de Proyectos/06 Cronograma 2.xlsx'),
    ],

    'sheet_names' => [
        'bank_plan_inversion' => 'F-PE-23 plan de inversion',
        'bank_plan_desarrollo' => 'F-PE-24 certi plan desarrol',
        'bank_cronograma' => 'F-PE-25 cronograma',
    ],

    'cells' => [
        'bank_plan_inversion' => [
            'codigo_dependencia' => 'B4',
            'dependencia' => 'D4',
            'proyecto' => 'B6',
            'vigencia' => 'K6',
            'valor_total_formula_cell' => 'D30',
            'firma_base_nombre' => 'A34',
            'firma_base_cargo' => 'A35',
            'firma_base_correo' => 'A36',
            'firma_base_telefono' => 'A37',
            'firma_elaboro_nombre' => 'F34',
            'firma_elaboro_cargo' => 'F35',
            'firma_elaboro_correo' => 'F36',
            'firma_elaboro_telefono' => 'F37',
            'firma_aprobo_nombre' => 'J34',
            'firma_aprobo_cargo' => 'J35',
            'firma_aprobo_correo' => 'J36',
            'firma_aprobo_telefono' => 'J37',
        ],
        'bank_plan_desarrollo' => [
            'codigo_dependencia' => 'C6',
            'dependencia' => 'G6',
            'proyecto' => 'C8',
            'vigencia' => 'K8',
            'firma_base_nombre' => 'B33',
            'firma_base_cargo' => 'B34',
            'firma_base_correo' => 'B35',
            'firma_base_telefono' => 'B36',
            'firma_elaboro_nombre' => 'F33',
            'firma_elaboro_cargo' => 'F34',
            'firma_elaboro_correo' => 'F35',
            'firma_elaboro_telefono' => 'F36',
            'firma_aprobo_nombre' => 'I33',
            'firma_aprobo_cargo' => 'I34',
            'firma_aprobo_correo' => 'I35',
            'firma_aprobo_telefono' => 'I36',
        ],
        'bank_cronograma' => [
            'dependencia' => 'B4',
            'proyecto' => 'B6',
            'vigencia' => 'O6',
            'fecha_firma' => 'A30',
            'firma_elaboro_nombre' => 'A34',
            'firma_elaboro_cargo' => 'A35',
            'firma_elaboro_correo' => 'A36',
            'firma_elaboro_telefono' => 'A37',
            'firma_aprobo_nombre' => 'G34',
            'firma_aprobo_cargo' => 'G35',
            'firma_aprobo_correo' => 'G36',
            'firma_aprobo_telefono' => 'G37',
        ],
    ],

    'table_rows' => [
        'bank_plan_inversion' => [
            'start_row' => 11,
            'columns' => [
                'producto_mga' => 'A',
                'beneficiarios' => 'B',
                'actividad' => 'C',
                'valor_actividad' => 'D',
                'codigo_fuente' => 'E',
                'nombre_fuente' => 'F',
                'meta_plan_codigo' => 'G',
                'meta_plan_nombre' => 'H',
                'municipio_relacion' => 'I',
            ],
        ],
        'bank_plan_desarrollo' => [
            'start_row' => 12,
            'columns' => [
                'actividad' => 'B',
                'valor_actividad' => 'C',
                'pilar' => 'D',
                'eje' => 'E',
                'linea' => 'F',
                'programa' => 'G',
                'subprograma' => 'H',
                'sector_texto_plantilla' => 'I',
                'meta_plan_codigo' => 'J',
                'meta_plan_nombre' => 'K',
            ],
        ],
        'bank_cronograma' => [
            'start_row' => 9,
            'columns' => [
                'actividad' => 'A',
                'ene' => 'B',
                'feb' => 'C',
                'mar' => 'D',
                'abr' => 'E',
                'may' => 'F',
                'jun' => 'G',
                'jul' => 'H',
                'ago' => 'I',
                'sep' => 'J',
                'oct' => 'K',
                'nov' => 'L',
                'dic' => 'M',
            ],
        ],
    ],

    'default_signatories' => [
        ['role' => 'formulador_oficial', 'orden' => 1],
        ['role' => 'elaboro', 'orden' => 2],
        ['role' => 'aprobo', 'orden' => 3],
    ],

    'default_activity_names' => [
        'REALIZAR PRELIMINARES',
        'REALIZAR DESMONTE Y DEMOLICIONES',
        'REALIZAR EXCAVACIONES',
        'REALIZAR RELLENOS',
        'REALIZAR CONCRETOS',
        'REALIZAR PISOS',
        'REALIZAR PINTURA',
        'RELIZAR MAMPOSTERIA',
        'REALIZAR ACERO FIGURADO',
        'REALIZAR ESTRUCTURAS METALICAS',
        'REALIZAR MALLA CONTRAPELOTAS',
        'REALIZAR CUBIERTA',
        'REALIZAR MOBILIARIO',
        'ELAIZAR INSTALACIONES SANITARIAS',
        'REALIZAR INSTALACIONES ELECTRICAS',
        'REALIZAR INTERVENTORIA',
        'REALIZAR BIENES O SERVICIOS ADICIONALES A LA OBRA PÚBLICA',
        'REALIZAR APOYO A LA SUPERVISIÓN',
        'REALIZAR COSTO ASOCIADO',
    ],
];
